# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: yt-dlp.FFmpeg
PackageVersion: N-127043-g5a54fcf75e-20260930
InstallerType: zip
NestedInstallerType: portable
Commands:
- ffmpeg
- ffplay
- ffprobe
ReleaseDate: 2026-09-30
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-N-127043-g5a54fcf75e-win32-gpl/bin/ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-N-127043-g5a54fcf75e-win32-gpl/bin/ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-N-127043-g5a54fcf75e-win32-gpl/bin/ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/yt-dlp/FFmpeg-Builds/releases/download/autobuild-2026-09-30-18-57/ffmpeg-N-127043-g5a54fcf75e-win32-gpl.zip
  InstallerSha256: D3170C0ECF219F3F57297C7C31CF1D0C247FAADF72B0D815DF49DF88B953CE70
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-N-127043-g5a54fcf75e-win64-gpl/bin/ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-N-127043-g5a54fcf75e-win64-gpl/bin/ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-N-127043-g5a54fcf75e-win64-gpl/bin/ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/yt-dlp/FFmpeg-Builds/releases/download/autobuild-2026-09-30-18-57/ffmpeg-N-127043-g5a54fcf75e-win64-gpl.zip
  InstallerSha256: 06ECDED6224D19EBA0C8597971C57EBF8E7614141B5F1ADCB3B250DD0FF343C7
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-N-127043-g5a54fcf75e-winarm64-gpl/bin/ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-N-127043-g5a54fcf75e-winarm64-gpl/bin/ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-N-127043-g5a54fcf75e-winarm64-gpl/bin/ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/yt-dlp/FFmpeg-Builds/releases/download/autobuild-2026-09-30-18-57/ffmpeg-N-127043-g5a54fcf75e-winarm64-gpl.zip
  InstallerSha256: 149161127FBC66DFED1F9EF251ED9D8FDB1ABACCB2117CEF364A90F286E21AE5
ManifestType: installer
ManifestVersion: 1.28.0
