# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Zen-Team.Zen-Browser.Twilight
PackageVersion: 1.18t
InstallerType: exe
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
  Custom: /DesktopShortcut=false
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2025-10-18
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/zen-browser/desktop/releases/download/twilight/zen.installer.exe
  InstallerSha256: 731992B1329897AF0318A8B450D9CF2184360FA72BC1A8295CE8825456B705EF
- Architecture: arm64
  InstallerUrl: https://github.com/zen-browser/desktop/releases/download/twilight/zen.installer-arm64.exe
  InstallerSha256: 381F7B800110C0E5D04300B499926879DF1664A5271AC38CEC97F5E1091C4ADF
ManifestType: installer
ManifestVersion: 1.10.0
