# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: jdx.mise
PackageVersion: 2026.10.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: mise/bin/mise-shim.exe
  PortableCommandAlias: mise-shim
- RelativeFilePath: mise/bin/mise.exe
  PortableCommandAlias: mise
UpgradeBehavior: install
ReleaseDate: 2026-10-05
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/jdx/mise/releases/download/v2026.10.3/mise-v2026.10.3-windows-x64.zip
  InstallerSha256: AF5CAD4D381C4E06E9C488AF86AD3D3159474FFA7A18E061436A408F7262F23A
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/jdx/mise/releases/download/v2026.10.3/mise-v2026.10.3-windows-arm64.zip
  InstallerSha256: 378CAD931510D02A840ECE40BDE9C7A69FC8D59F6902A24579E75A55BD19F279
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.28.0
