# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: pkgconf.pkgconf
PackageVersion: 3.0.8
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
UpgradeBehavior: install
ReleaseDate: 2026-10-08
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/pkgconf/pkgconf/releases/download/pkgconf-3.0.8/pkgconf-x86-3.0.8.msi
  InstallerSha256: 619E605414383963DE4FC819FAFFC99D48EF9DF9BD54FAB77D00882D008BE6C6
  ProductCode: '{AD9CA1A7-BEC1-4CA4-8A27-FE8459A4BC87}'
  AppsAndFeaturesEntries:
  - ProductCode: '{AD9CA1A7-BEC1-4CA4-8A27-FE8459A4BC87}'
    UpgradeCode: '{4FAEDAD2-3F9D-45CC-89A7-3732AD2DB0F7}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%/pkgconf-3.0.8'
- Architecture: x64
  InstallerUrl: https://github.com/pkgconf/pkgconf/releases/download/pkgconf-3.0.8/pkgconf-x64-3.0.8.msi
  InstallerSha256: A236479BBE403B202816745BEF19AFE2D6240606F28AB1F008BA0F33FBFAE43E
  ProductCode: '{111E05D9-C56F-445B-9AD2-46242B2E593A}'
  AppsAndFeaturesEntries:
  - ProductCode: '{111E05D9-C56F-445B-9AD2-46242B2E593A}'
    UpgradeCode: '{4FAEDAD2-3F9D-45CC-89A7-3732AD2DB0F7}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/pkgconf-3.0.8'
- Architecture: arm64
  InstallerUrl: https://github.com/pkgconf/pkgconf/releases/download/pkgconf-3.0.8/pkgconf-arm64-3.0.8.msi
  InstallerSha256: 5F79545C8C341030CA288AFE1EA1A9D264AE1BA107035812269C58FC09E9D7F0
  ProductCode: '{36DED988-FB45-4BB4-A462-6D6B44F30E7D}'
  AppsAndFeaturesEntries:
  - ProductCode: '{36DED988-FB45-4BB4-A462-6D6B44F30E7D}'
    UpgradeCode: '{4FAEDAD2-3F9D-45CC-89A7-3732AD2DB0F7}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/pkgconf-3.0.8'
ManifestType: installer
ManifestVersion: 1.28.0
