# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.28.0.schema.json

PackageIdentifier: PredatH0r.ChanSort
PackageVersion: 2026-10-08
PackageLocale: en-US
Publisher: PredatH0r
PublisherUrl: https://github.com/PredatH0r
PublisherSupportUrl: https://github.com/PredatH0r/ChanSort/issues
PackageName: ChanSort
PackageUrl: https://github.com/PredatH0r/ChanSort
License: GPLv3
ShortDescription: Process exported channel lists of many TVs' DTV and IDTV modes, and be able to import the processed lists back into the TV.
Moniker: chansort
Tags:
- antenna-television
- antenna-tv
- atsc
- chan-sort
- digital-terrestrial-television
- digital-tv
- digitalterrestrialtelevision
- digitaltv
- dtv
- dvb
- free-to-air
- idtv
- isdb
- satellite-tv
- tv-channel-lists
- tvchannellists
ReleaseNotes: |-
  Fixed wrong .zip package
  "Version 2026-10-07" accidentally had the .zip of the 2026-10-05 pre-release attached.
ReleaseNotesUrl: https://github.com/PredatH0r/ChanSort/releases/tag/v2026-10-08
ManifestType: defaultLocale
ManifestVersion: 1.28.0
