# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Genymobile.scrcpy
PackageVersion: 5.0.1
InstallerType: zip
NestedInstallerType: portable
ReleaseDate: 2026-10-08
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: scrcpy-win32-v5.0.1/scrcpy.exe
    PortableCommandAlias: scrcpy
  InstallerUrl: https://github.com/Genymobile/scrcpy/releases/download/v5.0.1/scrcpy-win32-v5.0.1.zip
  InstallerSha256: 0CB65EBF1BCE892FA4D1502D699AF0C7A1A7F24D7FEBCB9EF72894E3F23FC2AD
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: scrcpy-win64-v5.0.1/scrcpy.exe
    PortableCommandAlias: scrcpy
  InstallerUrl: https://github.com/Genymobile/scrcpy/releases/download/v5.0.1/scrcpy-win64-v5.0.1.zip
  InstallerSha256: B12A2C4EE8BE317422451FC7DCF8EE20A71B5EA7EF9AD73DDD825A25316227A5
- Architecture: arm64
  InstallerUrl: https://github.com/Genymobile/scrcpy/releases/download/v5.0.1/scrcpy-winarm64-v5.0.1.zip
  InstallerSha256: 16C3FC2068DF64946F670E3504B4752073EBAE47A416A45B46E79A5AB19C689B
ManifestType: installer
ManifestVersion: 1.28.0
