# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.28.0.schema.json

PackageIdentifier: Genymobile.scrcpy
PackageVersion: 5.0.1
PackageLocale: en-US
Publisher: Genymobile
PublisherUrl: https://github.com/Genymobile
PublisherSupportUrl: https://github.com/Genymobile/scrcpy/issues
PrivacyUrl: https://www.genymotion.com/privacy-statement/
Author: Romain Vimont
PackageName: scrcpy
PackageUrl: https://github.com/Genymobile/scrcpy
License: Apache-2.0
LicenseUrl: https://github.com/Genymobile/scrcpy/blob/HEAD/LICENSE
Copyright: Copyright (C) 2018-2024 Genymobile, Romain Vimont
CopyrightUrl: https://github.com/Genymobile/scrcpy/blob/v3.1/LICENSE
ShortDescription: Display and control your Android device
Description: This application mirrors Android devices (video and audio) connected via USB or over TCP/IP, and allows to control the device with the keyboard and the mouse of the computer. It does not require any root access.
Moniker: scrcpy
Tags:
- adb
- android
- audio
- control
- copy
- device
- display
- mirror
- record
- screen
- tcp
- usb
- video
ReleaseNotes: |-
  To receive a notification when a new release is available, click on Watch > Custom > Releases at the top.
  scrcpy v5.0.1
  Changes since v5.0:
  - Accept DRM_FORMAT_RG88 for NV12 chroma plane (#7070, #7073)
  - Fix H.265 hardware decoding on Windows (#7072)
  - Use the GPU of the renderer for VA-API decoding (#7075, #7081)
  - Force EGL only if VA-API is enabled (#7079)
  Highlights

  Hardware decoding fixes
  Scrcpy 5.0 introduced hardware decoding.
  This patch release (5.0.1) fixes several issues:
  - on Linux with an NVIDIA VA-API driver (#7070, #7073)
  - for H.265 on Windows depending on the driver (#7072)
  - with multiple GPUs on Linux, when decoding used a different GPU than rendering (#7075, #7081)
  - with the OpenGL renderer on Windows and macOS (#7079)
  - BlueSky: @scrcpy.bsky.social
  - Twitter: @scrcpy_app
  - Reddit: r/scrcpy
ReleaseNotesUrl: https://github.com/Genymobile/scrcpy/releases/tag/v5.0.1
Documentations:
- DocumentLabel: FAQ
  DocumentUrl: https://github.com/Genymobile/scrcpy/blob/v3.1/FAQ.md
ManifestType: defaultLocale
ManifestVersion: 1.28.0
