# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Anchore.Syft
PackageVersion: 1.54.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: syft.exe
UpgradeBehavior: install
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/anchore/syft/releases/download/v1.54.0/syft_1.54.0_windows_amd64.zip
  InstallerSha256: 77F4B472779058E819EEC9A054753A5071A996AAA40DB31A290F8B256748593F
- Architecture: arm64
  InstallerUrl: https://github.com/anchore/syft/releases/download/v1.54.0/syft_1.54.0_windows_arm64.zip
  InstallerSha256: 0FDFA61470A69B99ACE491DF1FD7EF9803439C15D4D3D19A0BCB139D8B9FBA4E
ManifestType: installer
ManifestVersion: 1.28.0
