# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Duplicati.Duplicati.Canary
PackageVersion: 2.4.0.103
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  InstallLocation: INSTALLLOCATION="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
ReleaseDate: 2026-10-02
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/duplicati/duplicati/releases/download/v2.4.0.103_canary_2026-10-02/duplicati-2.4.0.103_canary_2026-10-02-win-x86-gui.msi
  InstallerSha256: DE56AA3CF8A563522C4B539A9044ED011A4822192BB856F8DF5550688389E600
  ProductCode: '{9E88E083-352F-41A7-AC85-DFAE258F71C4}'
  AppsAndFeaturesEntries:
  - DisplayName: Duplicati
    ProductCode: '{9E88E083-352F-41A7-AC85-DFAE258F71C4}'
    UpgradeCode: '{1C94BC5A-2BF2-4273-9D8F-2CB30E780D16}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%/Duplicati 2'
- Architecture: x64
  InstallerUrl: https://github.com/duplicati/duplicati/releases/download/v2.4.0.103_canary_2026-10-02/duplicati-2.4.0.103_canary_2026-10-02-win-x64-gui.msi
  InstallerSha256: F27E118B217CFA63925C765AB89C1C20A8E69B293D16120CFF4820425056B312
  ProductCode: '{BF6A08BE-BA36-440F-B1EC-1B828C3C9E26}'
  AppsAndFeaturesEntries:
  - DisplayName: Duplicati
    ProductCode: '{BF6A08BE-BA36-440F-B1EC-1B828C3C9E26}'
    UpgradeCode: '{1C94BC5A-2BF2-4273-9D8F-2CB30E780D16}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/Duplicati 2'
- Architecture: arm64
  InstallerUrl: https://github.com/duplicati/duplicati/releases/download/v2.4.0.103_canary_2026-10-02/duplicati-2.4.0.103_canary_2026-10-02-win-arm64-gui.msi
  InstallerSha256: 854C47BAD07A855B164409A54035D2FE1C62C2D4BD56F8CF9038C64EA0A7E29F
  ProductCode: '{B34668C2-45CA-467D-9640-6D35CCAEFA0E}'
  AppsAndFeaturesEntries:
  - DisplayName: Duplicati
    ProductCode: '{B34668C2-45CA-467D-9640-6D35CCAEFA0E}'
    UpgradeCode: '{1C94BC5A-2BF2-4273-9D8F-2CB30E780D16}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/Duplicati 2'
ManifestType: installer
ManifestVersion: 1.28.0
