# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: astral-sh.ty
PackageVersion: 0.0.86
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ty.exe
InstallModes:
- silent
UpgradeBehavior: install
Commands:
- ty
ReleaseDate: 2026-10-09
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/astral-sh/ty/releases/download/0.0.86/ty-i686-pc-windows-msvc.zip
  InstallerSha256: 17F59909CB133E0A794863ED778D6E9643E82D2672C7890EB6111440EE864A93
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x86
- Architecture: x64
  InstallerUrl: https://github.com/astral-sh/ty/releases/download/0.0.86/ty-x86_64-pc-windows-msvc.zip
  InstallerSha256: 4E3444ADE1CA28F4020558388C31D715811AE4810612195264C71311A273083A
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/astral-sh/ty/releases/download/0.0.86/ty-aarch64-pc-windows-msvc.zip
  InstallerSha256: D62EFA70CD5590319E63011E997A641E36FD7814A674CF733AE81CBCB9350A83
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.28.0
