# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: yt-dlp.FFmpeg
PackageVersion: N-127014-g18ee27e67b-20260930
InstallerType: zip
NestedInstallerType: portable
Commands:
- ffmpeg
- ffplay
- ffprobe
ReleaseDate: 2026-09-30
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-N-127014-g18ee27e67b-win32-gpl/bin/ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-N-127014-g18ee27e67b-win32-gpl/bin/ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-N-127014-g18ee27e67b-win32-gpl/bin/ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/yt-dlp/FFmpeg-Builds/releases/download/autobuild-2026-09-30-00-16/ffmpeg-N-127014-g18ee27e67b-win32-gpl.zip
  InstallerSha256: 1CE98E1C246BC712B2EE1C3F4151A94DD9758D515EBA84785C6C1B1D3E800606
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-N-127014-g18ee27e67b-win64-gpl/bin/ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-N-127014-g18ee27e67b-win64-gpl/bin/ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-N-127014-g18ee27e67b-win64-gpl/bin/ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/yt-dlp/FFmpeg-Builds/releases/download/autobuild-2026-09-30-00-16/ffmpeg-N-127014-g18ee27e67b-win64-gpl.zip
  InstallerSha256: 3D0E8CBF23DE7D5702FD1B2125D944BF46F786943810B62E682F6F798BA2F0ED
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-N-127014-g18ee27e67b-winarm64-gpl/bin/ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-N-127014-g18ee27e67b-winarm64-gpl/bin/ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-N-127014-g18ee27e67b-winarm64-gpl/bin/ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/yt-dlp/FFmpeg-Builds/releases/download/autobuild-2026-09-30-00-16/ffmpeg-N-127014-g18ee27e67b-winarm64-gpl.zip
  InstallerSha256: 0727946AE73D4E1BB94BF25B478A5A97CA9D88C48A44B23CC3BE0C924F0A298C
ManifestType: installer
ManifestVersion: 1.28.0
