# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: WiresharkFoundation.Stratoshark
PackageVersion: 0.10.4
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ProductCode: Stratoshark
ReleaseDate: 2026-10-07
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Stratoshark'
Installers:
- Architecture: x64
  InstallerUrl: https://2.na.dl.wireshark.org/win64/all-versions/Stratoshark-0.10.4-x64.exe
  InstallerSha256: 90FBAC64C441B233D75A142A0400F8D40B33C5C4CB527EE61BB81BE4934DCD4B
  AppsAndFeaturesEntries:
  - Publisher: The Stratoshark developer community, https://www.wireshark.org
    ProductCode: Stratoshark
- Architecture: arm64
  InstallerUrl: https://2.na.dl.wireshark.org/win64/all-versions/Stratoshark-0.10.4-arm64.exe
  InstallerSha256: 83C5451DC419EC109965765E99AD6D8C7595304C3C921133A50F592221EF4BC4
  AppsAndFeaturesEntries:
  - DisplayName: Stratoshark 0.10.4 arm64
    Publisher: The Stratoshark developer community, https://www.wireshark.org
    ProductCode: Stratoshark
ManifestType: installer
ManifestVersion: 1.28.0
