# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Duplicati.Duplicati
PackageVersion: 2.4.0.1
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  InstallLocation: INSTALLLOCATION="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
ReleaseDate: 2026-10-07
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/duplicati/duplicati/releases/download/v2.4.0.1_stable_2026-10-07/duplicati-2.4.0.1_stable_2026-10-07-win-x86-gui.msi
  InstallerSha256: 46FA6276AFF7A8DDCCF4903FA537F9DFA2BD6F60D137BC68C761FC7D5F473D93
  ProductCode: '{F30C8B7E-E79D-48D5-80C1-6B0660D6F99D}'
  AppsAndFeaturesEntries:
  - ProductCode: '{F30C8B7E-E79D-48D5-80C1-6B0660D6F99D}'
    UpgradeCode: '{1C94BC5A-2BF2-4273-9D8F-2CB30E780D16}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%/Duplicati 2'
- Architecture: x64
  InstallerUrl: https://github.com/duplicati/duplicati/releases/download/v2.4.0.1_stable_2026-10-07/duplicati-2.4.0.1_stable_2026-10-07-win-x64-gui.msi
  InstallerSha256: 491B2CABEF0106CB7964A7CD2AE54A43CB2F2573D0B84C4AF00961D868E1B3B9
  ProductCode: '{AD9E5442-3C86-4905-A7C4-D8CC9F9A0EEF}'
  AppsAndFeaturesEntries:
  - ProductCode: '{AD9E5442-3C86-4905-A7C4-D8CC9F9A0EEF}'
    UpgradeCode: '{1C94BC5A-2BF2-4273-9D8F-2CB30E780D16}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/Duplicati 2'
- Architecture: arm64
  InstallerUrl: https://github.com/duplicati/duplicati/releases/download/v2.4.0.1_stable_2026-10-07/duplicati-2.4.0.1_stable_2026-10-07-win-arm64-gui.msi
  InstallerSha256: 859683382DFC37A004D06769029079355899EAE36FE3F29441E3D4FDC52FEA73
  ProductCode: '{402C3187-69F3-4DAD-92BD-B723EE9F3A00}'
  AppsAndFeaturesEntries:
  - ProductCode: '{402C3187-69F3-4DAD-92BD-B723EE9F3A00}'
    UpgradeCode: '{1C94BC5A-2BF2-4273-9D8F-2CB30E780D16}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/Duplicati 2'
ManifestType: installer
ManifestVersion: 1.28.0
