# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: jdx.mise
PackageVersion: 2026.10.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: mise/bin/mise-shim.exe
  PortableCommandAlias: mise-shim
- RelativeFilePath: mise/bin/mise.exe
  PortableCommandAlias: mise
UpgradeBehavior: install
ReleaseDate: 2026-10-03
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/jdx/mise/releases/download/v2026.10.1/mise-v2026.10.1-windows-x64.zip
  InstallerSha256: 390194BFBE7FDE45C9C6C810521909C3B59417073C142FE0FB414101D058BB86
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/jdx/mise/releases/download/v2026.10.1/mise-v2026.10.1-windows-arm64.zip
  InstallerSha256: BB30714FBA91D63BF56E5A51972D64DFDCF5ACE80865CFBD2D947F101AB01064
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.28.0
