# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: JesseDuffield.lazygit
PackageVersion: 0.66.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: lazygit.exe
ReleaseDate: 2026-10-05
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/jesseduffield/lazygit/releases/download/v0.66.0/lazygit_0.66.0_Windows_32-bit.zip
  InstallerSha256: ED067613BEF886F3C28DAA2170FA24E58DB4719DE04FD7B14AFA29D95F17B015
- Architecture: x64
  InstallerUrl: https://github.com/jesseduffield/lazygit/releases/download/v0.66.0/lazygit_0.66.0_Windows_x86_64.zip
  InstallerSha256: ED8FAB4AF7B8BAC474084E976214A96569DEA841C9F9B293502B83D8C3163E4B
- Architecture: arm64
  InstallerUrl: https://github.com/jesseduffield/lazygit/releases/download/v0.66.0/lazygit_0.66.0_Windows_arm64.zip
  InstallerSha256: 53BE33B36DC83B32AFF317E317C7B34495AB8C15D4360DB7BA56B12B05E7D157
ManifestType: installer
ManifestVersion: 1.28.0
