# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Hashicorp.Vault
PackageVersion: 2.1.2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: vault.exe
ReleaseDate: 2026-10-07
Installers:
- Architecture: x86
  InstallerUrl: https://releases.hashicorp.com/vault/2.1.2/vault_2.1.2_windows_386.zip
  InstallerSha256: 27011A6EE766815845670161B1A98FA207993C884A06151FC984537A14E4EBFA
- Architecture: x64
  InstallerUrl: https://releases.hashicorp.com/vault/2.1.2/vault_2.1.2_windows_amd64.zip
  InstallerSha256: F5B2342BA6605EC9225EAFA5AC47C6E45D325A54FAE8F2393D88D3DD8C5454A9
ManifestType: installer
ManifestVersion: 1.28.0
