# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: jdx.usage
PackageVersion: 6.12.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: usage.exe
Commands:
- usage
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/jdx/usage/releases/download/v6.12.0/usage-x86_64-pc-windows-msvc.zip
  InstallerSha256: BC9E362FD5169A9A13EB943963C905BB60F3FD2BD1076336C2BEB2878209BC24
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/jdx/usage/releases/download/v6.12.0/usage-aarch64-pc-windows-msvc.zip
  InstallerSha256: 2CDB29A06EDB66C4ED4CBA0136FF6BED394139410F346F77673A66268A0F39FD
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
