# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Streetwriters.Notesnook
PackageVersion: 3.4.9
UpgradeBehavior: install
Commands:
- notesnook
ReleaseDate: 2026-10-06
Installers:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/streetwriters/notesnook/releases/download/v3.4.9/notesnook_win_x64.exe
  InstallerSha256: 902E6DE6C4DB38ABD6488B10EF4C314297BD28291CA6ABBA104428CEA6DAB071
  ProductCode: a05a6719-4910-5e6c-a2aa-9af71cd1063b
  AppsAndFeaturesEntries:
  - ProductCode: a05a6719-4910-5e6c-a2aa-9af71cd1063b
- Architecture: x64
  InstallerType: portable
  InstallerUrl: https://github.com/streetwriters/notesnook/releases/download/v3.4.9/notesnook_win_x64_portable.exe
  InstallerSha256: 12FAF532BA979498490EB44296A5CBC9ED9F8D352531A0BA3A4F52CE63D75C50
- Architecture: arm64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/streetwriters/notesnook/releases/download/v3.4.9/notesnook_win_arm64.exe
  InstallerSha256: 1F03325E5C1DE79600AFE388900D0CD8525BBE51B321193180AF27F921A82B73
  ProductCode: a05a6719-4910-5e6c-a2aa-9af71cd1063b
  AppsAndFeaturesEntries:
  - ProductCode: a05a6719-4910-5e6c-a2aa-9af71cd1063b
- Architecture: arm64
  InstallerType: portable
  InstallerUrl: https://github.com/streetwriters/notesnook/releases/download/v3.4.9/notesnook_win_arm64_portable.exe
  InstallerSha256: 9DBFBA5BF5118617B0CBF2419A3834DF46D92FB8F544972586BCF06AFBF74058
ManifestType: installer
ManifestVersion: 1.28.0
