# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Bazel.Bazel
PackageVersion: 9.3.0
InstallerType: portable
Commands:
- bazel
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/bazelbuild/bazel/releases/download/9.3.0/bazel-9.3.0-windows-x86_64.exe
  InstallerSha256: 64AFF24F986DF98291F4DA2795FD4B3E831C0AF3F74BD7AA8EB56C49CB28B1E3
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/bazelbuild/bazel/releases/download/9.3.0/bazel-9.3.0-windows-arm64.exe
  InstallerSha256: 6E3735E844E37E06CDF3A22778AEB451D47A2165E27E52A7AF0C98F45030BD37
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.28.0
