# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: SQLite.SQLite
PackageVersion: 3.54.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: sqldiff.exe
  PortableCommandAlias: sqldiff
- RelativeFilePath: sqlite3.exe
  PortableCommandAlias: sqlite3
- RelativeFilePath: sqlite3_analyzer.exe
  PortableCommandAlias: sqlite3_analyzer
- RelativeFilePath: sqlite3_rsync.exe
  PortableCommandAlias: sqlite3_rsync
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  InstallerUrl: https://www.sqlite.org/2026/sqlite-tools-win-x64-3540000.zip
  InstallerSha256: 63CB06E952A83FD140139B008ED5B47496608161C62F8CD17BC96E8BEB1DE029
- Architecture: arm64
  InstallerUrl: https://www.sqlite.org/2026/sqlite-tools-win-arm64-3540000.zip
  InstallerSha256: 050646357F5D0A4D2914794297060C19A46361CADEACC9906420EEBBE04582A5
ManifestType: installer
ManifestVersion: 1.28.0
