# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: OpenTofu.Tofu
PackageVersion: 1.13.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: tofu.exe
UpgradeBehavior: install
ReleaseDate: 2026-10-01
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/opentofu/opentofu/releases/download/v1.13.1/tofu_1.13.1_windows_386.zip
  InstallerSha256: 822B7B07D15332B54A9C26A07753FCE53F246C87DE292AA7CF113685C44584DE
- Architecture: x64
  InstallerUrl: https://github.com/opentofu/opentofu/releases/download/v1.13.1/tofu_1.13.1_windows_amd64.zip
  InstallerSha256: 5B653D1D95719EEEC4CCF55F0E2102081B6F589D788197F1CABEB89CBD4078A7
ManifestType: installer
ManifestVersion: 1.28.0
