# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.28.0.schema.json

PackageIdentifier: OpenTofu.Tofu
PackageVersion: 1.13.1
PackageLocale: en-US
Publisher: The Linux Foundation
PublisherUrl: https://opentofu.org/
PublisherSupportUrl: https://github.com/opentofu/opentofu/issues
PackageName: OpenTofu
PackageUrl: https://github.com/opentofu/opentofu
License: MPL-2.0
LicenseUrl: https://github.com/opentofu/opentofu/blob/HEAD/LICENSE
Copyright: Copyright (c) The Linux Foundation
CopyrightUrl: https://github.com/opentofu/opentofu/blob/main/LICENSE
ShortDescription: OpenTofu lets you declaratively manage your cloud infrastructure.
Moniker: tofu
ReleaseNotes: |-
  BUG FIXES:
  - tofu show -json <planfile> now works again when ephemeral resources are present in the configuration. (4623).
  - Ephemeral output values are now always re-evaluated during the apply phase, instead of sometimes using stale values from the planning phase. (#4582)
ReleaseNotesUrl: https://github.com/opentofu/opentofu/releases/tag/v1.13.1
ManifestType: defaultLocale
ManifestVersion: 1.28.0
