# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Git.GCM
PackageVersion: 3.0.1
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-10-06
Installers:
- Architecture: x64
  InstallerType: inno
  Scope: user
  InstallerUrl: https://github.com/git-ecosystem/git-credential-manager/releases/download/v3.0.1/gcmuser-win-x64-3.0.1.exe
  InstallerSha256: 723F9E13C360D56F9B0DFDB0609B4EDD8A28C0B33ECCB4DE900039EA56B3517A
  ProductCode: '{aa76d31d-432c-42ee-844c-bc0bc801cef3}}_is1'
  AppsAndFeaturesEntries:
  - ProductCode: '{aa76d31d-432c-42ee-844c-bc0bc801cef3}}_is1'
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Programs\Git Credential Manager'
- Architecture: x64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://github.com/git-ecosystem/git-credential-manager/releases/download/v3.0.1/gcm-win-x64-3.0.1.exe
  InstallerSha256: B2DC87F5DEB70DD605ECA646E987EC9841CD7BE74453C6E3066AC50BB3D3C98B
  ProductCode: '{fdfae50a-1bc1-4ead-9228-1e1c275e8d12}}_is1'
  AppsAndFeaturesEntries:
  - ProductCode: '{fdfae50a-1bc1-4ead-9228-1e1c275e8d12}}_is1'
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Git Credential Manager'
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: git-credential-manager.exe
  InstallerUrl: https://github.com/git-ecosystem/git-credential-manager/releases/download/v3.0.1/gcm-win-x64-3.0.1.zip
  InstallerSha256: BC51ABD9E613A856F909B5EA9244B5A265A4FC8A85383E2982D76034D80CFE3F
- Architecture: arm64
  InstallerType: inno
  Scope: user
  InstallerUrl: https://github.com/git-ecosystem/git-credential-manager/releases/download/v3.0.1/gcmuser-win-arm64-3.0.1.exe
  InstallerSha256: 9BADD7B738C6687BC01E5DF2D5B637A709AFEFAE99D8C792A52843624197225D
  ProductCode: '{aa76d31d-432c-42ee-844c-bc0bc801cef3}}_is1'
  AppsAndFeaturesEntries:
  - ProductCode: '{aa76d31d-432c-42ee-844c-bc0bc801cef3}}_is1'
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Programs\Git Credential Manager'
- Architecture: arm64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://github.com/git-ecosystem/git-credential-manager/releases/download/v3.0.1/gcm-win-arm64-3.0.1.exe
  InstallerSha256: 704E5EA8BC5AF3DF2E3CF6228893B39673843A6BE8C30B4F6FC57C3D817C871E
  ProductCode: '{fdfae50a-1bc1-4ead-9228-1e1c275e8d12}}_is1'
  AppsAndFeaturesEntries:
  - ProductCode: '{fdfae50a-1bc1-4ead-9228-1e1c275e8d12}}_is1'
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Git Credential Manager'
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: git-credential-manager.exe
  InstallerUrl: https://github.com/git-ecosystem/git-credential-manager/releases/download/v3.0.1/gcm-win-arm64-3.0.1.zip
  InstallerSha256: B282E6D8A2EC5047B420D28E895DC7DB73529F9A98015A9FF9BE31327C056D77
ManifestType: installer
ManifestVersion: 1.28.0
