# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.28.0.schema.json

PackageIdentifier: OpenBao.OpenBao
PackageVersion: 2.7.1
PackageLocale: en-US
Publisher: OpenBao
PublisherUrl: https://openbao.org/
PublisherSupportUrl: https://github.com/openbao/openbao/issues
Author: OpenBao a Series of LF Projects, LLC
PackageName: OpenBao
PackageUrl: https://openbao.org/
License: MPL-2.0
LicenseUrl: https://github.com/openbao/openbao/blob/HEAD/LICENSE
Copyright: Copyright (c) 2015 HashiCorp, Inc.
CopyrightUrl: https://github.com/openbao/openbao/blob/main/LICENSE
ShortDescription: OpenBao is a software solution to manage, store, and distribute sensitive data.
Description: |-
  OpenBao exists to provide a software solution to manage, store, and distribute sensitive data including secrets, certificates, and keys.
  The OpenBao community intends to provide this software under an OSI-approved open-source license, led by a community run under open governance principles.
Moniker: openbao
Tags:
- certificates
- credentials
- encryption
- keys
- openbao
- secrets
- secrets-management
- security
- vault
ReleaseNotes: |-
  SECURITY
  - core: Prevent disclosure of tls_acme_eab_mac_key from sys/config/state/sanitized. GHSA-3237-j65r-m5rp. [GH-4148]
  - core/audit: The unauthenticated "Root Token Generation" and "Rekey" endpoints (which are disabled by default) returned their response, even if audit logging failed. GHSA-q74w-hv5x-6hxf. [GH-4148]
  - auth/approle: Ensure Secret ID cannot be used for authentication after expiration but before tidy is called. GHSA-7m59-mp95-w6ph. [GH-4148]
  - auth/approle: Fix incorrect JSON-decode path when parsing login requests with form data bodies. GHSA-5v22-543h-wg96. [GH-4148]
  - auth/cert: Fix omission of TLS connection propagation when calculating role-based quota. GHSA-5v22-543h-wg96. [GH-4148]
  - auth/kubernetes: Ensure Service Account JWT is validated on renewal, preventing post-revoke usage. GHSA-gf3j-hm38-jhh5. [GH-4148]

  CHANGES
  - packaging: Update the default server config included in Linux packages to use the pebbledb backend instead of the removed file backend. [GH-4088]

  BUG FIXES
  - core/barrier: Persist updates to key rotation config on changes to disabled field. [GH-4107]
  - core/grpc-invalidation: Ensure dispatcher lifecycle correctly handles active, standby state changes without locking conflicts. Resolves GRPC invalidation drops and pre-seal active node hangs. [GH-4117]
  - storage/raft: Fix auto_join breaking on providers that include ports with their discovered addresses. [GH-4113]
  - storage/postgresql: Switch to pg_last_wal_replay_lsn() for applied index value checks. [GH-4118]
  - api: Honor the error backoff interval after failed LifetimeWatcher renewal attempts. [GH-4036]

  What's Changed
  - docs(guides): add migration guide for File to PebbleDB storage backends on Kubernetes (#4092 by @pree) backported by @pree in #4109
  - Update default config included in linux packages (#4088 by @satoqz) by @satoqz in #4121
  - KeyRotationConfig equals() method should compare disabled field (#4107 by @wslabosz-reply) backported by @satoqz in #4122
  - Use persistent JobManager in GRPC Invalidation (#4117 by @cipherboy) backported by @satoqz in #4123
  - Fix Auto Join with provider-specified port (#4113 by @satoqz) backported by @satoqz in #4124
  - Honor backoff after failed LifetimeWatcher renewals (#4036 by @haxonittech) backported by @satoqz in #4125
  - Swap to pg_last_wal_replay_lsn() (#4118 by @cipherboy) backported by @satoqz in #4126
  - Ensure release artifact signatures are verified on creation (#3838 by @cipherboy) backported by @satoqz in #4128
  - Bump ubi10-minimal from e3a5632 to 204e153 (#4129 by @dependabot) backported by @satoqz in #4138
  - Bump github.com/hashicorp/cap from 0.13.0 to 0.14.0 (#4133 by @dependabot) backported by @satoqz in #4143
  - v2.7.1 - Security Fixes against release/v2.7.x #4146 by @06kellyjac, @cipherboy, @phil9909, @satoqz, @wslabosz-reply) backported by @cipherboy in #4147
  - Add release notes for v2.7.1 by @satoqz in #4149
ReleaseNotesUrl: https://github.com/openbao/openbao/releases/tag/v2.7.1
Documentations:
- DocumentLabel: Documentation
  DocumentUrl: https://openbao.org/docs/
ManifestType: defaultLocale
ManifestVersion: 1.28.0
