# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: OpenBao.OpenBao
PackageVersion: 2.7.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: bao.exe
  PortableCommandAlias: bao
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/openbao/openbao/releases/download/v2.7.1/openbao_2.7.1_windows_amd64.zip
  InstallerSha256: E3B3335918A78CC730BB07014C4191C80FE5EB376F3F1A708185ACF8BC0109AC
- Architecture: arm64
  InstallerUrl: https://github.com/openbao/openbao/releases/download/v2.7.1/openbao_2.7.1_windows_arm64.zip
  InstallerSha256: BA1675FB515FEF5150A402C759D37ECBE48E6961C05C3ACC8B69DDAC37BB584D
ManifestType: installer
ManifestVersion: 1.28.0
