# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: astral-sh.ty
PackageVersion: 0.0.85
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ty.exe
InstallModes:
- silent
UpgradeBehavior: install
Commands:
- ty
ReleaseDate: 2026-10-06
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/astral-sh/ty/releases/download/0.0.85/ty-i686-pc-windows-msvc.zip
  InstallerSha256: CE1A1760F5E6BF52522BBA88F620349568816655EFBDA85D94106A93E487A6F4
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x86
- Architecture: x64
  InstallerUrl: https://github.com/astral-sh/ty/releases/download/0.0.85/ty-x86_64-pc-windows-msvc.zip
  InstallerSha256: D03974C578A0F1842F8548737435CCEA415119DEAEC7EE8D1EBBEF716E50FD8C
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/astral-sh/ty/releases/download/0.0.85/ty-aarch64-pc-windows-msvc.zip
  InstallerSha256: 4D166F2D91845E4AEE43F7068AB433B59A332C6FAEC281D87283AD7B9E2D1726
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.28.0
