# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: jj-vcs.jj
PackageVersion: 0.46.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: jj.exe
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/jj-vcs/jj/releases/download/v0.46.0/jj-v0.46.0-x86_64-pc-windows-msvc.zip
  InstallerSha256: C42316B10DF04611BC65029A18BCB2D92636EDDDB6871D511F7BB4233E999B83
- Architecture: arm64
  InstallerUrl: https://github.com/jj-vcs/jj/releases/download/v0.46.0/jj-v0.46.0-aarch64-pc-windows-msvc.zip
  InstallerSha256: F6F0552D0E292E3E62AA7FD21F4B15E9B6644D4939DB908ED6D6B04B5B0A7907
ManifestType: installer
ManifestVersion: 1.28.0
