# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: tree-sitter.tree-sitter-cli
PackageVersion: 0.27.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: tree-sitter.exe
  PortableCommandAlias: tree-sitter
ReleaseDate: 2026-10-08
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/tree-sitter/tree-sitter/releases/download/v0.27.1/tree-sitter-cli-windows-x86.zip
  InstallerSha256: 62CDF6606FF46EAAFE5AAE1CA0AA6EA2096E793958B41D4F34DDE8771C4B9F50
- Architecture: x64
  InstallerUrl: https://github.com/tree-sitter/tree-sitter/releases/download/v0.27.1/tree-sitter-cli-windows-x64.zip
  InstallerSha256: DE043E4C289EFCEF7981DF99988300F23763BEFDEB36ABF7C1898F080C478424
- Architecture: arm64
  InstallerUrl: https://github.com/tree-sitter/tree-sitter/releases/download/v0.27.1/tree-sitter-cli-windows-arm64.zip
  InstallerSha256: EADBB00C87C5A38F874EB92AF593DF7264635AFEFB455AF3218BDB1C50123BAD
ManifestType: installer
ManifestVersion: 1.28.0
