# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: CXWorld.CapFrameX
PackageVersion: 1.9.1.4
InstallerType: zip
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.10
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  NestedInstallerType: burn
  NestedInstallerFiles:
  - RelativeFilePath: CapFrameXBootstrapper.exe
  Scope: machine
  InstallerUrl: https://github.com/CXWorld/CapFrameX/releases/download/v1.9.1/release_1.9.1_installer.zip
  InstallerSha256: 2AB5B172619C0E6E8A848432E687AC491FDC9F9CF9CF1521D17F580712E01117
  AppsAndFeaturesEntries:
  - ProductCode: '{CAFA764E-4EC1-4FDF-B842-91DBC0107C67}'
    UpgradeCode: '{D124F3FF-D15F-4B43-BD0D-CD631DD931DA}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\CapFrameX'
- Architecture: x64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: CapFrameX.exe
    PortableCommandAlias: capframex
  InstallerUrl: https://github.com/CXWorld/CapFrameX/releases/download/v1.9.1/release_1.9.1_portable.zip
  InstallerSha256: 0E95C6E8893E67AAFA3BF14CB9BF0E1F35AD3302DC39B89EC0365D8A24AD04A8
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
