# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Ethereum.geth
PackageVersion: 1.17.8
InstallerType: nullsoft
Scope: machine
ProductCode: Ethereum Geth
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- DisplayName: Ethereum - Geth - Official Go implementation of the Ethereum protocol
  DisplayVersion: 1.17.8-a5790770
  ProductCode: Ethereum Geth
Installers:
- Architecture: x64
  InstallerUrl: https://gethstore.blob.core.windows.net/builds/geth-windows-amd64-1.17.8-a5790770.exe
  InstallerSha256: 2073165AB61785F8488A56909CEE2FC08592384ABA95C1B68534FE99DB756379
ManifestType: installer
ManifestVersion: 1.28.0
