# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Arelle.Arelle
PackageVersion: 2.46.1
UpgradeBehavior: install
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://github.com/Arelle/Arelle/releases/download/2.46.1/arelle-win-2.46.1.exe
  InstallerSha256: 98340576AE6447FDEF636719C78B50FCADE40905ACD30CCC311CC5300CD04B5E
  ProductCode: Arelle
  AppsAndFeaturesEntries:
  - Publisher: arelle.org
    ProductCode: Arelle
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Arelle'
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: arelleCmdLine.exe
    PortableCommandAlias: arelleCmdLine
  - RelativeFilePath: arelleGUI.exe
    PortableCommandAlias: arelleGUI
  InstallerUrl: https://github.com/Arelle/Arelle/releases/download/2.46.1/arelle-win-2.46.1.zip
  InstallerSha256: FD6C1C22B2817253F10BD85A869702A55272BC8B86E8E17B0E154011E2F35F1F
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.28.0
