# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.28.0.schema.json

PackageIdentifier: Anchore.Syft
PackageVersion: 1.54.1
PackageLocale: en-US
Publisher: Anchore Inc
PublisherUrl: https://anchore.com/
PublisherSupportUrl: https://github.com/anchore/syft/issues
PackageName: Syft
PackageUrl: https://github.com/anchore/syft
License: Apache-2.0
LicenseUrl: https://github.com/anchore/syft/blob/HEAD/LICENSE
ShortDescription: CLI tool and library for generating a Software Bill of Materials from container images and filesystems
Description: Syft is a powerful and easy-to-use open-source tool for generating Software Bill of Materials (SBOMs) for container images and filesystems. It provides detailed visibility into the packages and dependencies in your software, helping you manage vulnerabilities, license compliance, and software supply chain security.
Moniker: syft
Tags:
- containers
- cyclonedx
- docker
- go
- golang
- hacktoberfest
- oci
- sbom
- spdx
- static-analysis
- tool
ReleaseNotes: |-
  Bug Fixes
  - resolve packages.lock dependencies deterministically [PR #5210 @spiffcs]
  - Cannot produce attestation file from local podman image [Issue #1664] [PR #5368 @Bru456]

  Dependencies
  9 dependency changes (9 updated).
  Updated (9 packages)
  - github.com/anchore/go-rpmdb v0.2.0 → v0.2.2
  - github.com/anchore/stereoscope v0.3.3 → v0.3.4
  - github.com/docker/cli v29.8.1+incompatible → v29.8.2+incompatible
  - github.com/glebarez/go-sqlite v1.20.3 → v1.23.0
  - github.com/klauspost/compress v1.20.0 → v1.20.1
  - github.com/secure-systems-lab/go-securesystemslib v0.11.0 → v0.11.1
  - github.com/sigstore/protobuf-specs v0.5.1 → v0.5.2
  - github.com/sigstore/sigstore v1.10.8 → v1.10.11
  - github.com/sylabs/sif/v2 v2.24.1 → v2.24.2
  (Full Changelog)
ReleaseNotesUrl: https://github.com/anchore/syft/releases/tag/v1.54.1
ManifestType: defaultLocale
ManifestVersion: 1.28.0
