# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PredatH0r.ChanSort
PackageVersion: 2026-09-28
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ChanSort_2026-09-28/ChanSort.exe
  PortableCommandAlias: chansort
InstallerSuccessCodes:
- -1978334972
FileExtensions:
- amdb
- bin
- cdp
- chl
- conf
- csv
- db
- dbm
- dvbs
- lamedb
- m3u
- mtk
- radio
- scm
- sdx
- tar
- tll
- tv
- txt
- xml
- zip
ReleaseDate: 2026-09-28
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/PredatH0r/ChanSort/releases/download/v2026-09-28/ChanSort_2026-09-28.zip
  InstallerSha256: 9FB547B4923416AE4437255B45EC7BD6E9DC13BCA06A7D2CD8A2EFD252395C46
ManifestType: installer
ManifestVersion: 1.12.0
