# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: PredatH0r.ChanSort
PackageVersion: 2026-09-28
PackageLocale: en-US
Publisher: PredatH0r
PublisherUrl: https://github.com/PredatH0r
PublisherSupportUrl: https://github.com/PredatH0r/ChanSort/issues
PackageName: ChanSort
PackageUrl: https://github.com/PredatH0r/ChanSort
License: GPLv3
ShortDescription: Process exported channel lists of many TVs' DTV and IDTV modes, and be able to import the processed lists back into the TV.
Moniker: chansort
Tags:
- antenna-television
- antenna-tv
- atsc
- chan-sort
- digital-terrestrial-television
- digital-tv
- digitalterrestrialtelevision
- digitaltv
- dtv
- dvb
- free-to-air
- idtv
- isdb
- satellite-tv
- tv-channel-lists
- tvchannellists
ReleaseNotes: |-
  - Samsung .zip: fixed support for lists containing IP-TV channels with a missing "default_url" field
  - Samsung .zip: if there is more than 1 channel with the same program number, then all are shown now.
    Previous versions only showed the first channel for each given number
  - added support for Novaler channel_list.xml file format
  - updated reference lists für Sky on Astra 28.8 and RTL 102.5 on Hotbird 13F
ReleaseNotesUrl: https://github.com/PredatH0r/ChanSort/releases/tag/v2026-09-28
ManifestType: defaultLocale
ManifestVersion: 1.12.0
