# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: jdx.usage
PackageVersion: 6.12.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: usage.exe
Commands:
- usage
ReleaseDate: 2026-10-06
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/jdx/usage/releases/download/v6.12.1/usage-x86_64-pc-windows-msvc.zip
  InstallerSha256: B5F1E3FAA5DEA4FFF179BDEF2E9AC737D2D416496FB9332E0D686E9A4A7B6D2C
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/jdx/usage/releases/download/v6.12.1/usage-aarch64-pc-windows-msvc.zip
  InstallerSha256: 98BEDAC7B5177483B817A52AFC8D7A63A8107013F41119BF2C5D2220D436D094
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.28.0
